# Generated by Django 3.1.7 on 2022-07-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220708_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sub_headline',
        ),
    ]
